#!/usr/bin/python3
import tempfile
import subprocess
import logging
import os.path

logging.basicConfig(level=logging.DEBUG)

def symtab(elf):
    d = tempfile.NamedTemporaryFile()
    logging.info("reading symtab of %s", elf)
    subprocess.check_call(['readelf', '-s', elf],
                            stdout = d)
    return d

def diff_obj(args, symtab, old, new):
    name = os.path.commonprefix([old, new]).rstrip("-_.")
    patch_file = args.prefix + name + ".o"
    cmd = ['create-diff-object', old, new, 'main', symtab, "IGNORED", name, patch_file]
    logging.info("Create Patch: %s", cmd)
    subprocess.check_call(cmd)
    return patch_file

if __name__ == "__main__":
    import sys, argparse
    parser = argparse.ArgumentParser("create-patch")
    parser.add_argument("elf",   help="ELF file of original binary")
    parser.add_argument("--obj", "-o", nargs=2, metavar=("OLD", "NEW"),
                        action='append',default=[],required=True,
                        help="Pair of old and new binary")
    parser.add_argument("--prefix", "-p", default="patch-",
                        help="What prefix should be used for the patch objects")
    args = parser.parse_args(sys.argv[1:])

    symbols = symtab(args.elf)

    patches = []
    for obj in args.obj:
        fn = diff_obj(args, symbols.name, obj[0], obj[1])
        patches.append(fn)

    print("WF_PATCH_QUEUE=\"{};\"".format(",".join(patches)))
